# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('tresbps', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fbs', models.IntegerField()),
                ('restecg', models.IntegerField()),
                ('thalach', models.IntegerField()),
                ('exchang', models.IntegerField()),
                ('oldpeak', models.FloatField()),
                ('slope', models.FloatField()),
                ('ca', models.IntegerField()),
                ('thal', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
