# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='exchang',
            new_name='exang',
        ),
    ]
